// This file was generated by Prisma, and assumes you run Prisma commands using `bun --bun run prisma [command]`.
import "dotenv/config";
import { defineConfig } from "prisma/config";

const user = encodeURIComponent(process.env.DB_USER || "postgres");
const password = encodeURIComponent(process.env.DB_PASSWORD || "");
const host = process.env.DB_HOST || "localhost";
const port = parseInt(process.env.DB_PORT || "5432", 10);
const dbName = process.env.DB_NAME || "mydb";
const schema = process.env.DB_SCHEMA || "public";
const databaseUrl = `postgresql://${user}:${password}@${host}:${port}/${dbName}?schema=${schema}`;

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
    seed: "bun prisma/seed.ts"
  },
  datasource: {
    url: databaseUrl,
  },
});
